version: '3.8'

services:
  api:
    build:
      context: ./api
      dockerfile: Dockerfile
    container_name: api
    ports:
      - "3000:3000"
    environment:
      - LLM_HOST=http://127.0.0.1:1234
    networks:
      - app-network

  ui:
    build:
      context: ./ui
      dockerfile: Dockerfile
    container_name: my_ui_container
    ports:
      - "7860:7860"
    # environment:
    depends_on:
      - api
    networks:
      - app-network

networks:
  app-network:
    driver: bridge